### ISSUE TITLE
Should provide also related g-c-c patch

### ISSUE THREAD

**Issue by 3v1n0** [puxplaying/mutter-x11-scaling#10]
In particular patches are
 - https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/0019-display-Support-UI-scaled-logical-monitor-mode.patch
 - https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/0024-display-Allow-fractional-scaling-to-be-enabled.patch

These allow proper multi-display management and toggle the option?

**Comment by puxplaying** [comment]
Thank you for the info Marco, will try to build with this patches.

**Comment by puxplaying** [comment]
> In particular patches are
> 
>     * https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/0019-display-Support-UI-scaled-logical-monitor-mode.patch
> 
>     * https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/0024-display-Allow-fractional-scaling-to-be-enabled.patch
> 
> 
> These allow proper multi-display management and toggle the option?

I've uploaded a gnome-control-center PKGBUILD with this patches which can be found here:
https://github.com/puxplaying/gnome-control-center-x11-scaling

**Comment by puxplaying** [comment]
https://github.com/puxplaying/gnome-control-center-x11-scaling provides the related g-c-c patches
Thank you @3v1n0 !
