### ISSUE TITLE
Conflict with mutter

### ISSUE THREAD

**Issue by leontepe** [puxplaying/mutter-x11-scaling#16]
When trying to build this package from source and installing it using `makepkg -srci`, I get a conflict with the `mutter` package itself.

```
==> Installing package mutter-x11-scaling with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...
:: mutter-x11-scaling and mutter are in conflict. Remove mutter? [y/N]
```
At this point, it doesn't matter which option I choose. It fails either way.

Y:
```
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: mutter-x11-scaling and mutter are in conflict
==> WARNING: Failed to install built package(s).
==> Cleaning up...
```

n:
```
error: failed to prepare transaction (could not satisfy dependencies)
:: removing mutter breaks dependency 'libmutter-7.so=0-64' required by gnome-shell
==> WARNING: Failed to install built package(s).
==> Cleaning up...
```

What can I do about this?

**Comment by yochananmarqos** [comment]
@leontepe I can't reproduce it. The package provides and conflicts with `mutter` as it should. There's a more updated PKGBUILD [here](https://gitlab.manjaro.org/packages/extra/mutter-x11-scaling), try that.

**Comment by puxplaying** [comment]
@leontepe It seems you are trying to build the package on the stable branch as it requires `libmutter-7` - 
This will not work until gnome 40 will be pushed to stable.
