### ISSUE TITLE
Build fails for both AUR and git versions.

### ISSUE THREAD

**Issue by lemonistas** [puxplaying/mutter-x11-scaling#17]
Hi, I tried to build the package today but build fails with Kernel 5.13.5-arch1-1 on Arch Linux. 
[meson-log.txt](https://github.com/puxplaying/mutter-x11-scaling/files/6895395/meson-log.txt)

**Comment by puxplaying** [comment]
Hi, the attached meson-log does unfortunately not contain any useful information, please build the package via `makepkg -srci` as described. On my end it does build fine.

**Comment by lemonistas** [comment]
I'm very sorry I must have uploaded the wrong log. I did try to build it exactly as described with `makepkg -srci` but the check fails. Please find the test log attached to this message (I hope it's the right log with useful information for you). 

Thank you very much!
[testlog.txt](https://github.com/puxplaying/mutter-x11-scaling/files/6901552/testlog.txt)

**Comment by puxplaying** [comment]
Are you able to build the [upstream](https://github.com/archlinux/svntogit-packages/tree/packages/mutter/trunk) arch package successfully?

**Comment by lemonistas** [comment]
I just checked and apparently I am not able to build the upstream arch package successfully even though I have installed both `base-devel` and `git`. 
[testlog.txt](https://github.com/puxplaying/mutter-x11-scaling/files/6903085/testlog.txt)

**Comment by puxplaying** [comment]
From the log it seems like there is something wrong with the local build environment as it throws way too many warnings and errors. I would suggest to either try building it in a VM or in a [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot).

**Comment by lemonistas** [comment]
Okay thanks for the advice, I'll try building in a clean chroot. 
Again, I'm sorry for opening an issue that apparently wasn't one.

**Comment by puxplaying** [comment]
Don't worry, I hope you can find the culprit!
