### ISSUE TITLE
Merge with upstream

### ISSUE THREAD

**Issue by mimbrero** [puxplaying/mutter-x11-scaling#25]
This works perfectly fine, even Ubuntu and others include this patch by default, so why isn't this merged with mutter yet?

**Comment by puxplaying** [comment]
Hi, glad to hear that it works for you!
Unfortunately I cant give you a proper answer for the reason why this has not been up-streamed yet. 
Marco Trevisan (@3v1n0) from Canonical is the developer of this patch and also a contributor to upstream mutter.

In my opinion it would be better to ask this question on Ubuntu.

**Comment by InetAddress** [comment]
Ok, I think Marco won't reply to this issue, so I'll ask on Ubuntu. Thank you!

Should we leave this open to prevent future duplicates?

**Comment by mind-overflow** [comment]
@InetAddress in case you posted this on Ubuntu, would you mind sharing the link? So we can track the progress here too and have a reference.

**Comment by puxplaying** [comment]
> Paru asked me if I wanted to replace "mutter-x11-scaling" (this version)

This is most likely a case of the AUR package being out of date.

> makes me wonder if this has maybe already been merged?

That is not the case unfortunately.

**Comment by InetAddress** [comment]
Hello.

Sorry for the late reply, I completely ignored the notification 😅

I haven't opened the issue yet. I'll reply to this one when I create it, don't worry, I'm a little busy right now with other stuff. If someone opens one before me, just reply to this. Thanks!

**Comment by puxplaying** [comment]
As it stands, this patch will most likely not be forwarded to upstream Mutter as there seems to be no interest.

https://github.com/puxplaying/mutter-x11-scaling/blob/04abe964ac9c0cb829f8067cc1570d7ec0f86cfa/x11-Add-support-for-fractional-scaling-using-Randr.patch#L9
> Forwarded: No, forwarding is not planned as there's no upstream interest
