### ISSUE TITLE
makepkg error: I am a freshman in linux, could you tell me what to do next, please!

### ISSUE THREAD

**Issue by xyx2333** [puxplaying/mutter-x11-scaling#31]
I have the nvidia 3060laptop and the manjaro version is 22.0.0
This is the shell output:
  Options
    Wayland                 : True
    Wayland EGLStream       : True
    Native Backend          : True
    EGL Device              : True
    Remote desktop          : True
    libgnome-desktop        : True
    gudev                   : True
    Wacom                   : True
    SM                      : True
    Startup notification    : True
    Introspection           : True
    Documentation           : False
    Profiler                : True
    Xwayland initfd         : True
    Xwayland listenfd       : True
    Safe X11 I/O errors     : True
    Xwayland terminate delay: True

  Tests
    Enabled                 : True
    Core tests              : True
    Cogl tests              : True
    Clutter tests           : True
    KVM tests               : False
    Installed tests         : False
    Coverage                : False

  User defined options
    auto_features           : enabled
    buildtype               : plain
    libexecdir              : lib
    prefix                  : /usr
    sbindir                 : bin
    wrap_mode               : nodownload
    b_lto                   : true
    b_pie                   : true
    egl_device              : true
    installed_tests         : false
    wayland_eglstream       : true

Found ninja-1.11.1 at /usr/bin/ninja
ninja: Entering directory `/home/xyx/MySoft/mutter-x11-scaling/src/build'
[277/1171] Compiling C object clutter/...-10.so.0.0.0.p/clutter-frame-clock.c.o
../mutter/clutter/clutter/clutter-frame-clock.c: In function ‘clutter_frame_clock_notify_presented’:
../mutter/clutter/clutter/clutter-frame-clock.c:236:15: warning: unused variable ‘debug_state’ [-Wunused-variable]
  236 |   const char *debug_state =
      |               ^~~~~~~~~~~
[415/1171] Generating cogl/cogl/Cogl-1... command (wrapped by meson to set env)
FAILED: cogl/cogl/Cogl-10.gir 
/usr/bin/meson --internal exe --unpickle /home/xyx/MySoft/mutter-x11-scaling/src/build/meson-private/meson_exe_g-ir-scanner_fff3d87ffa9acaab8af07802822ad9f29d421892.dat
while executing ['/usr/bin/g-ir-scanner', '--no-libtool', '--namespace=Cogl', '--nsversion=10', '--warn-all', '--output', 'cogl/cogl/Cogl-10.gir', '--c-include=cogl/cogl.h', '--quiet', '-U_GNU_SOURCE', '-UCOGL_COMPILATION', '-D__COGL_H_INSIDE__', '-D__COGL_XLIB_H_INSIDE__', '-D__COGL_EGL_H_INSIDE__', '-D__COGL_GLX_H_INSIDE__', '-DCOGL_GIR_SCANNING', '-I/home/xyx/MySoft/mutter-x11-scaling/src/mutter/cogl/cogl', '-I/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/cogl', '-I/home/xyx/MySoft/mutter-x11-scaling/src/mutter/cogl/.', '-I/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/.', '-I/home/xyx/MySoft/mutter-x11-scaling/src/mutter/cogl/cogl', '-I/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/cogl', '--filelist=/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/cogl/libmutter-cogl-10.so.0.0.0.p/Cogl_10_gir_filelist', '--include=cairo-1.0', '--include=GL-1.0', '--include=GObject-2.0', '--include=Graphene-1.0', '--cflags-begin', '-D_GNU_SOURCE', '-I/home/xyx/MySoft/mutter-x11-scaling/src/mutter/cogl/.', '-I/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/.', '-I/home/xyx/MySoft/mutter-x11-scaling/src/mutter/cogl/cogl', '-I/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/cogl', '-I/usr/include/glib-2.0', '-I/usr/lib/glib-2.0/include', '-I/usr/include/sysprof-4', '-I/usr/include/gio-unix-2.0', '-I/usr/include/libmount', '-I/usr/include/blkid', '-I/usr/include/graphene-1.0', '-I/usr/lib/graphene-1.0/include', '-I/usr/include/cairo', '-I/usr/include/lzo', '-I/usr/include/libpng16', '-I/usr/include/freetype2', '-I/usr/include/harfbuzz', '-I/usr/include/pixman-1', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/gobject-introspection-1.0', '--cflags-end', '--add-include-path=/usr/share/gir-1.0', '-L/home/xyx/MySoft/mutter-x11-scaling/src/build/cogl/cogl', '--library', 'mutter-cogl-10', '-lglib-2.0', '-lgio-2.0', '-lgobject-2.0', '-lgraphene-1.0', '-lwayland-server', '-lEGL', '-lX11', '-lGL', '-lGLESv2', '-lcairo', '-lgmodule-2.0', '-lgdk_pixbuf-2.0', '-lsysprof-capture-4', '-lXext', '-lXfixes', '-lXdamage', '-lXcomposite', '-lXrandr', '-lm', '-lgirepository-1.0']
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'

[432/1171] Linking target cogl/tests/conform/test-conformance
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
==> Removing installed dependencies...
checking dependencies...
:: lv2 optionally requires python-markdown: for lv2specgen.py
:: lv2 optionally requires python-pygments: for lv2specgen.py
:: pipewire optionally requires pipewire-session-manager: Session manager
:: python-pyparsing optionally requires python-jinja: for generating Railroad Diagrams
:: smbclient optionally requires python-markdown: for samba-tool domain schemeupgrade

Packages (20) gi-docgen-2022.1-1  gobject-introspection-1.72.0-1
              libdazzle-3.44.0-1  meson-0.63.2-1  ninja-1.11.1-1
              python-dbusmock-0.28.4-1  python-importlib-metadata-4.8.3-1
              python-jinja-1:3.1.2-2  python-mako-1.2.2-1
              python-markdown-3.4.1-1  python-markupsafe-2.1.1-1
              python-pygments-2.13.0-1  python-smartypants-2.0.1-9
              python-toml-0.10.2-7  python-typogrify-2.0.7-13
              python-zipp-3.8.1-1  sysprof-3.44.0-2  wayland-protocols-1.26-1
              wireplumber-0.4.11-4  xorg-server-xvfb-21.1.4-1

Total Removed Size:  50.73 MiB

:: Do you want to remove these packages? [Y/n] y

**Comment by puxplaying** [comment]
If you use Manjaro, there is no need to compile this package. Simply install  _mutter-x11-scaling_ from the repository.

**Comment by xyx2333** [comment]
> If you use Manjaro, there is no need to compile this package. Simply install _mutter-x11-scaling_ from the repository.

I am so sorry to ask the simple question but I really do not know how to install this repository simply, I just know use makepkg to install pkgbuild.Could you please tell me how to do this? What command I should use?

**Comment by puxplaying** [comment]
Open add/remove software, type **mutter-x11-scaling** and click on install.
Or in a terminal execute: `sudo pacman -Syu mutter-x11-scaling`

This package is already available on [Manjaro](https://packages.manjaro.org/?query=mutter-x11). See also [here](https://forum.manjaro.org/t/howto-gnome-xorg-fractional-per-monitor-scaling/49318).

**Comment by xyx2333** [comment]
> Open add/remove software, type **mutter-x11-scaling** and click on install.
> Or in a terminal execute: `sudo pacman -Syu mutter-x11-scaling`
> 
> This package is already available on [Manjaro](https://packages.manjaro.org/?query=mutter-x11). See also [here](https://forum.manjaro.org/t/howto-gnome-xorg-fractional-per-monitor-scaling/49318).

Thank you so much!!!
