### ISSUE TITLE
BUILD fails at x11-Add-support-for-fractional-scaling-using-Randr.patch

### ISSUE THREAD

**Issue by jaro3** [puxplaying/mutter-x11-scaling#34]
makefile fails with:

==> Validating source files with sha256sums...
    mutter ... Skipped
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... FAILED
    Support-Dynamic-triple-double-buffering.patch ... Passed
==> ERROR: One or more files did not pass the validity check!

with --skipchecksums:

patching file src/backends/meta-monitor-config-manager.c
Hunk #4 succeeded at 759 with fuzz 1 (offset 28 lines).
Hunk #5 succeeded at 1904 with fuzz 2 (offset 1125 lines).
Hunk #6 FAILED at 893.
Hunk #7 FAILED at 912.
Hunk #8 FAILED at 935.
Hunk #9 FAILED at 1178.
Hunk #10 FAILED at 1763.
Hunk #11 FAILED at 1799.
6 out of 11 hunks FAILED -- saving rejects to file src/backends/meta-monitor-config-manager.c.rej

**Comment by puxplaying** [comment]
This is user error, simply follow the instructions in the readme.

**Comment by jaro3** [comment]
wget https://salsa.debian.org/gnome-team/mutter/-/raw/$_scaling_commit/debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch
--2022-12-11 23:28:20--  https://salsa.debian.org/gnome-team/mutter/-/raw//debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving salsa.debian.org (salsa.debian.org)... 209.87.16.44, 2607:f8f0:614:1::1274:44
Connecting to salsa.debian.org (salsa.debian.org)|209.87.16.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-11 23:28:21 ERROR 404: Not Found.

**Comment by jaro3** [comment]
There is only this (old version?): 

https://salsa.debian.org/gnome-team/mutter/-/raw/1853489070cb6bf1b743aa3b888613030ff094f9/debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch

can you provide downloadable link for the latest x11-Add-support-for-fractional-scaling-using-Randr.patch

**Comment by puxplaying** [comment]
> There is only this (old version?):
>
> https://salsa.debian.org/gnome-team/mutter/-/raw/1853489070cb6bf1b743aa3b888613030ff094f9/debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch
>
> can you provide downloadable link for the latest x11-Add-support-for-fractional-scaling-using-Randr.patch

I have no idea what you are trying to build, but it is obviously not the [current PKGBUILD](https://github.com/puxplaying/mutter-x11-scaling/blob/12be87ce97f01a574f408a6fadab2194c83c5f1d/PKGBUILD#L32) in this repo as the commit is wrong. Simply follow the instructions in the readme and clone the git repo, then build the package.
