### ISSUE TITLE
==> ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by rchalamala** [puxplaying/mutter-x11-scaling#4]
I cloned the git repo, and when I used makepkg -srci, I got this error? The only way to get around it was to use --skipinteg, but then when I tried changing my scaling, and I'd get a black screen and be back to 100% like before?

**Comment by puxplaying** [comment]
Thank you for the report, seems i forgot to update the pkgsum which is fixed now.
https://github.com/puxplaying/mutter-x11-scaling/commit/9063a18c7dc1402430111c3f2aa1008c9f281da5

> but then when I tried changing my scaling, and I'd get a black screen and be back to 100% like before?

This patch is experimental and may not work in every case. Are there any error logs you could share?

Please also note that this patch does currently not build with `mutter 3.36.2` but `3.36.1` which could also be a source of failure if the rest of the gnome stack is at 3.36.2.

**Comment by rchalamala** [comment]
Where would I look for the error logs, I haven't used gnome very much. I'm on mutter 3.36.1. What happens is that, I'll click 150%, click apply, my screen will go black for a few seconds, turn back on, and it'll be 100% again.

**Comment by puxplaying** [comment]
I have just pushed a updated patch from [Upstream](https://salsa.debian.org/gnome-team/mutter/-/blob/ubuntu/master/debian/patches/x11-Add-support-for-fractional-scaling-using-Randr.patch) and updated to `mutter-3.36.2-1`.
Please try this build.

**Comment by rchalamala** [comment]
I have to be doing something wrong. It still does the same thing, and this is a fresh Manjaro install. So far, I update all packages (I do have base-devel, I checked multiple times), then I git clone, I cd to the folder, run makepkg -srci, and I say yes to everything. At the end it asks if you want to reinstall mutter, should I say no?

**Comment by puxplaying** [comment]
Make sure that the package is mutter-3.36.2-1 and say yes.

> Edit: Is ~/.config/monitors.xml supposed to exist by default, it's not in ~/.config/

Maybe you need to first make some changes to System Settings' Display for the file to get created.
It is at least there on my system.

**Comment by rchalamala** [comment]
I think I'm just doing it wrong, I reinstalled Manjaro, and made sure the file was there, and I still had the same problem.
