### ISSUE TITLE
AUR 45.0+r49+g8d3d8b86e5-1 version error

### ISSUE THREAD

**Issue by FelixFourcolor** [puxplaying/mutter-x11-scaling#41]
After installing this version (the latest one at the time of writing), running `yay` shows that this package still has a new update. Updating it installs the same already-installed version. And repeat.

![Screenshot from 2023-10-22 01-05-50](https://github.com/puxplaying/mutter-x11-scaling/assets/34260584/dea682a9-08e9-41a1-8bd2-445368e30365)
![Screenshot from 2023-10-22 01-06-28](https://github.com/puxplaying/mutter-x11-scaling/assets/34260584/2ac7f610-f4dd-41bc-b54b-82ba71c2450b)

I think the issue is that the package is labeled version `45.0+r49+g8d3d8b86e5-1` on the AUR, but the PKGBUILD installs version `45.0+r49+g8d3d8b86e-1`.

(I've verified that the issue is not with `yay`. Installing manually has the same effect.)

**Comment by puxplaying** [comment]
Should be fixed with the mutter point release, please test and report.
https://github.com/puxplaying/mutter-x11-scaling/commit/3d1baa95b3f8aa52f8d63b9aaab852c92677aa2d

**Comment by FelixFourcolor** [comment]
It works. Thank you.
