### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by icepie** [puxplaying/mutter-x11-scaling#42]

**Comment by puxplaying** [comment]
Hey everyone!

Unfortunately there is currently no [upstream patch](https://salsa.debian.org/gnome-team/mutter/-/blob/ubuntu/latest/debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch?ref_type=heads) which would apply to stable Mutter 46, as Ubuntu is using a early RC version for their LTS release. Re-basing the patch was not enough as it also requires code changes, which are out of my scope.

I guess we will have to wait for upstream Ubuntu to fix the patch.

**Comment by Hyphaed** [comment]
@puxplaying  which version of mutter you recommend to apply the patch?

I've downloaded 45 from https://gitlab.gnome.org/GNOME/mutter

applied this same patch but then failed when compiling

**Comment by Hyphaed** [comment]
I'm using this script that runs evevery time that I logIn at Gnome (also with that I do not have problem with VMWare + 2 screens)


thanks @runsisi I will try it later....

[scale_script.txt](https://github.com/puxplaying/mutter-x11-scaling/files/14776318/scale_script.txt)


also lock screen ooption dissapeared from Power Off options

org.gnome.desktop   disable-lock-screen  option is off

and also the bold text on gnome terminal, I'm missing it

**Comment by puxplaying** [comment]
Thanks for the contribution @runsisi .
I've adapted some missing changes to your re-based patch and pushed it to the [mutter-46](https://github.com/puxplaying/mutter-x11-scaling/tree/mutter-46) branch. Please test and report!

**Comment by Hyphaed** [comment]
@puxplaying 

I've just tried your patch (for the sake of it)

the scale options are not showing on gnome-control-center, yet I'm happy with the scaling script I'm using nowadays

**Comment by puxplaying** [comment]
> the scale options are not showing on gnome-control-center

Did you try it with the [g-c-c 46 version](https://github.com/puxplaying/gnome-control-center-x11-scaling/tree/mutter-46) that I pushed today? For me at least it works fine.

**Comment by caribo** [comment]
Fractional scaling is working for me with new 46 branches. Thanks!

Only  issue I have is pacman -Syuu wanting to downgrade the packages to 45 .. don't know if this is expected / normal.

```
: Synchronising package databases...
 core                  147.2 KiB  50.7 KiB/s 00:03 [#####################] 100%
 extra                   8.7 MiB  1454 KiB/s 00:06 [#####################] 100%
 multilib              144.1 KiB  97.8 KiB/s 00:01 [#####################] 100%
:: Starting full system upgrade...
warning: gnome-control-center-x11-scaling: downgrading from version 46.0.1-1 to version 45.3-2
warning: mutter-x11-scaling: downgrading from version 46.0-1 to version 45.5-1
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mutter-x11-scaling (45.5-1) breaks dependency 'libmutter-14.so=0-64' required by gnome-shell

```

**Comment by puxplaying** [comment]
> Fractional scaling is working for me with new 46 branches. Thanks!
> 
> Only issue I have is pacman -Syuu wanting to downgrade the packages to 45 .. don't know if this is expected / normal.

Thanks for testing, glad to hear that it works for you, so I can consider pushing this packages to the main branches and the AUR. 

The issue with pacman wanting to downgrade your packages is because you're using `-Syuu` (downgrade) instead of `-Syu`. 

This is expected according to the synced branches in your output, because you don't have  this packages in a local custom repository added to your `/etc/pacman.conf` for example. I wrote [autogit](https://github.com/puxplaying/autogit) to handle this and other cases, but you need to know about how pacman and arch repos in general are working in order to use it.

**Comment by Hyphaed** [comment]
@puxplaying 

I see...

I'm on Debian/Ubuntu base system

I've compiled mutter and gnome-control-center from gnome sources not from

https://github.com/puxplaying/gnome-control-center-x11-scaling/tree/mutter-46

in case I want to build https://github.com/puxplaying/gnome-control-center-x11-scaling/tree/mutter-46

which commands I should use?

**Comment by puxplaying** [comment]
@Hyphaed 

I've no experience with building packages on a debian based system, but in general it should be as simple as applying the two provided patches to g-c-c  and build the package. The same that you would do with mutter-x11-scaling I guess.

**Comment by Hyphaed** [comment]
it just get stuck on patching and shows nothing if I add the flag --verbose, mutter patched without problems using your other patch

ferran@z590i:~/Documents/PersonalPackages/gnome-control-center$ patch -p1 display-Allow-fractional-scaling-to-be-enabled.patch --verbose
