### ISSUE TITLE
Unable to update to 46.0.4

### ISSUE THREAD

**Issue by muhammadalkady** [puxplaying/mutter-x11-scaling#44]
Hello, I am getting an error while updating to 46.0.4
```
The Meson build system
Version: 1.4.0
Source dir: /home/muhammad/.cache/yay/mutter-x11-scaling/src/mutter
Build dir: /home/muhammad/.cache/yay/mutter-x11-scaling/src/build
Build type: native build
Project name: mutter
Project version: 46.0
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports link arguments -Wl,--disable-new-dtags: YES 
Library m found: YES
Found pkg-config: YES (/home/linuxbrew/.linuxbrew/bin/pkg-config) 0.29.2
Found CMake: /usr/bin/cmake (3.29.2)
Run-time dependency graphene-gobject-1.0 found: NO (tried pkgconfig and cmake)

mutter/meson.build:109:15: ERROR: Dependency "graphene-gobject-1.0" not found, tried pkgconfig and cmake

A full log can be found at /home/muhammad/.cache/yay/mutter-x11-scaling/src/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: mutter-x11-scaling-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
mutter-x11-scaling - exit status 4
```
I have already installed this package
https://archlinux.org/packages/extra/x86_64/graphene

**Comment by puxplaying** [comment]
Hi, I can't reproduce this issue.

 - This looks really weird and more like a mirror issue to me, are your mirrors up to date? 
 - Have you tried to build it manually via "`makepkg`" as described in the readme, to exclude any "yay" issues? 
 - I would also recommend to try building it via [devtools](https://archlinux.org/packages/?name=devtools) ([Convenience way](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Convenience_way)) in a clean chroot in case the issue persists with "`makepkg`".

**Comment by muhammadalkady** [comment]
I have removed homebrew from the path, after that I am getting a successful build. Any ideas why?

**Comment by puxplaying** [comment]
> I have removed homebrew from the path, after that I am getting a successful build. Any ideas why?

Well I've never used it, so I can only speculate. However, if the issue is reproducible with homebrew it should be reported upstream.
