### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by lukasreinert** [puxplaying/mutter-x11-scaling#46]
Hi there,
first I want to thank you for your work! You're doing a great job!
I have the AUR version of mutter-x11-scaling and when updating my arch pc I get the following error:

> :: (1/1) Parsing SRCINFO: mutter-x11-scaling
> ==> Making package: mutter-x11-scaling 46.3.1-1 (Mon 08 Jul 2024 08:15:44 PM CEST)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Updating mutter git repo...
>   -> Found x11-Add-support-for-fractional-scaling-using-Randr.patch
>   -> Found Support-Dynamic-triple-double-buffering.patch
>   -> Found mutter-fix-x11-restart.patch
> ==> Validating source files with b2sums...
>     mutter ... Passed
>     x11-Add-support-for-fractional-scaling-using-Randr.patch ... FAILED
>     Support-Dynamic-triple-double-buffering.patch ... FAILED
>     mutter-fix-x11-restart.patch ... Passed
> ==> ERROR: One or more files did not pass the validity check!
>  -> error making: mutter-x11-scaling-exit status 1
>  -> Failed to install the following packages. Manual intervention is required:
> mutter-x11-scaling - exit status 1

**Comment by puxplaying** [comment]
> x11-Add-support-for-fractional-scaling-using-Randr.patch ... FAILED
> Support-Dynamic-triple-double-buffering.patch ... FAILED
> ==> ERROR: One or more files did not pass the validity check!

Hi there, please clear the cache of your build directory and try it  again, the patches have been updated with the latest release.

I would suggest to always build mutter in clean environment, as patches are frequently updated., to avoid such errors.

**Comment by lukasreinert** [comment]
That was a quite easy fix. Thank you so much. I'll keep it im mind.
