### ISSUE TITLE
Issues after the gnome 47 upgrade

### ISSUE THREAD

**Issue by simprince** [puxplaying/mutter-x11-scaling#48]
I am on arch. After upgrading gnome to 47, this package failed with the following error message:

=> Validating source files with b2sums...
    mutter ... Passed
    gvdb ... Passed
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/USERNAME/.cache/yay/mutter-x11-scaling 
	 context: exit status 1 
	 

:: (1/1) Parsing SRCINFO: mutter-x11-scaling
==> Making package: mutter-x11-scaling 47.0-1 (Thu 19 Sep 2024 04:45:01 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating mutter git repo...
  -> Updating gvdb git repo...
  -> Found x11-Add-support-for-fractional-scaling-using-Randr.patch
==> Validating source files with b2sums...
    mutter ... Passed
    gvdb ... Passed
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: mutter-x11-scaling-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
mutter-x11-scaling - exit status 1

**Comment by simprince** [comment]
Just read another closed issue and find the fix. I go into the mentioned .cache folder and rm the .patch file there. Re-run yay to upgrade and it works.

**Comment by simprince** [comment]
Now I face another issue. When I try to apply the 150% scaling, it says 'Changes cannot be applied. .... due to hardware limitation'

**Comment by simprince** [comment]
> Now I face another issue. When I try to apply the 150% scaling, it says 'Changes cannot be applied. .... due to hardware limitation'

My temporary fix was to revert the change to my ~/.config/monitors.xml back to the one with the 150% scaling. Restart my computer. Obvious this is not as convenient as being able to set this in the setting UI.

**Comment by puxplaying** [comment]
> Now I face another issue. When I try to apply the 150% scaling, it says 'Changes cannot be applied. .... due to hardware limitation'

Do you happen to use a multi monitor setup? And if so, do you have gnome-control-center-x11-scaling installed?

What is the output of `gnome-control-center -v` when you try to apply the scale?

Some have reported that restarting the computer seems to help working around this issue.

**Comment by simprince** [comment]
> > Now I face another issue. When I try to apply the 150% scaling, it says 'Changes cannot be applied. .... due to hardware limitation'
> 
> Do you happen to use a multi monitor setup? And if so, do you have gnome-control-center-x11-scaling installed?
> 
> What is the output of `gnome-control-center -v` when you try to apply the scale?
> 
> Some have reported that restarting the computer seems to help working around this issue.

I only have my laptop built-in monitor and no external monitor. I have restarted multiple times. Restarting helps reset to my monitors.xml but it doesn't fix the 'unable to change to 150% in settings' issue.

**Comment by simprince** [comment]
This is my gnome-control-center -v output when I update the scaling setting:

07:08:19.9819     cc-display-panel[ 3353]: WARNING: Config not applicable: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Monitor mode size doesn't match scaled monitor layout
07:08:22.4405     cc-display-panel[ 3353]:   DEBUG: setting adjustment 20.000 to 8:00
07:08:22.4406     cc-display-panel[ 3353]:   DEBUG: setting adjustment 6.000 to 6:00

**Comment by puxplaying** [comment]
> 07:08:19.9819 cc-display-panel[ 3353]: WARNING: Config not applicable: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Monitor mode size doesn't match scaled monitor layout

It may be worth to try if https://github.com/puxplaying/gnome-control-center-x11-scaling solves the issue.

**Comment by simprince** [comment]
> > 07:08:19.9819 cc-display-panel[ 3353]: WARNING: Config not applicable: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Monitor mode size doesn't match scaled monitor layout
> 
> It may be worth to try if https://github.com/puxplaying/gnome-control-center-x11-scaling solves the issue.

That seems to work! Thanks.

**Comment by simprince** [comment]
Now I faced another issue during 'yay -S mutter-x11-scaling'

==> Validating source files with b2sums...
    mutter ... Passed
    gvdb ... Passed
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... Passed
    0001-Revert_window_wayland_Use_scale_for_configured_rect_in_configuration.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: mutter-x11-scaling-exit status 1

**Comment by fernandesafp** [comment]
I also have the same problem, even after removing everything inside ~/.cache. I get the same by cloning this repository.

My output:
```
yay -S mutter-x11-scaling                          ✔  15:26:22 
AUR Explicit (1): mutter-x11-scaling-47.0-3
:: PKGBUILD up to date, skipping download: mutter-x11-scaling
  1 mutter-x11-scaling               (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 mutter-x11-scaling               (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: mutter-x11-scaling 47.0-3 (Wed 02 Oct 2024 15:26:27 WEST)
==> Retrieving sources...
  -> Cloning mutter git repo...
Cloning into bare repository '/home/andre/.cache/yay/mutter-x11-scaling/mutter'...
remote: Enumerating objects: 248591, done.
remote: Counting objects: 100% (203502/203502), done.
remote: Compressing objects: 100% (23440/23440), done.
remote: Total 248591 (delta 193476), reused 180316 (delta 180062), pack-reused 45089 (from 1)
Receiving objects: 100% (248591/248591), 93.60 MiB | 15.28 MiB/s, done.
Resolving deltas: 100% (193476/193476), done.
  -> Cloning gvdb git repo...
Cloning into bare repository '/home/andre/.cache/yay/mutter-x11-scaling/gvdb'...
remote: Enumerating objects: 326, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 326 (delta 78), reused 125 (delta 72), pack-reused 193 (from 1)
Receiving objects: 100% (326/326), 102.82 KiB | 431.00 KiB/s, done.
Resolving deltas: 100% (191/191), done.
  -> Downloading x11-Add-support-for-fractional-scaling-using-Randr.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  119k  100  119k    0     0  2402k      0 --:--:-- --:--:-- --:--:-- 2447k
  -> Downloading 0001-Revert_window_wayland_Use_scale_for_configured_rect_in_configuration.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1978    0  1978    0     0   8352      0 --:--:-- --:--:-- --:--:--  8345
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with b2sums...
    mutter ... Passed
    gvdb ... Passed
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... Passed
    0001-Revert_window_wayland_Use_scale_for_configured_rect_in_configuration.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/andre/.cache/yay/mutter-x11-scaling
	 context: exit status 1
	

:: (1/1) Parsing SRCINFO: mutter-x11-scaling
==> Making package: mutter-x11-scaling 47.0-3 (Wed 02 Oct 2024 15:26:47 WEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating mutter git repo...
  -> Updating gvdb git repo...
  -> Found x11-Add-support-for-fractional-scaling-using-Randr.patch
  -> Found 0001-Revert_window_wayland_Use_scale_for_configured_rect_in_configuration.patch
==> Validating source files with b2sums...
    mutter ... Passed
    gvdb ... Passed
    x11-Add-support-for-fractional-scaling-using-Randr.patch ... Passed
    0001-Revert_window_wayland_Use_scale_for_configured_rect_in_configuration.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: mutter-x11-scaling-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
mutter-x11-scaling - exit status 1
```
