### ISSUE TITLE
Desktop Icons broken

### ISSUE THREAD

**Issue by HannesJo0139** [puxplaying/mutter-x11-scaling#6]
Using a fresh Manjaro Gnome Setup. Everything working like a charm but the Desktop Icons disappear. Trying to get them back by deactivating -> reactivating icons can just produce some graphic artifacts. No Desktop Icons at all. :(

**Comment by puxplaying** [comment]
I just tested it with the `gnome-shell-extension-desktop-icons-ng` from Manjaro repo and it works fine on my end. What extension do you use?

**Comment by HannesJo0139** [comment]
That is really weird since I was sitting on a fresh setup, using default extension as well. May be an issue regarding younger releases? 
However, that was something like my last try of getting manjaro setup in a satisfactory way. I stepped back to Mint right now. So I am ok with closing the issue.
