### ISSUE TITLE
Scaling options don't update after installation

### ISSUE THREAD

**Issue by westleyfsm** [puxplaying/mutter-x11-scaling#7]
Installed on Manjaro Gnome. I only have 100% and 200%. I have tried resetting the mutter settings, rebooting, restarting mutter, all to no avail.

Appreciate the work done!

**Comment by puxplaying** [comment]
Do you mean that `gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"` does not work for you? Have you build the package from source or did you install the binary from release page?

**Comment by westleyfsm** [comment]
Correct. I built from source

**Comment by puxplaying** [comment]
Has this package worked for you before or is this the first try? Please also check if `mutter-x11-sc` from the Manjaro repos works for you.

**Comment by westleyfsm** [comment]
Installing that package worked.
